export {
  KANBAN_COLUMN_COMPACT_THRESHOLD,
  KANBAN_COLUMN_HEIGHT_CLASS,
  KANBAN_COLUMN_WIDTH_CLASS,
  KANBAN_BOARD_OUTER_CLASS,
  KANBAN_SCROLL_CLASS,
  KANBAN_COLUMNS_ROW_CLASS,
} from '@/lib/ui/kanban-layout';
